# Repository info
[repository]
name = "hyprscrolling"
authors = ["Vaxry and community"]
hyprland-headers = true

# Plugin info
[hyprscrolling]
description = "A plugin to add a scrolling layout"
authors = ["Vaxry"]
output = "hyprscrolling.so"
build = [
    "make"
]
